/**
 * ABI for the ENSPremiumRegistrar contract.
 */
export const ensPremiumRegistrarAbi = [
  {
    type: 'function',
    name: 'commitPurchase',
    inputs: [{ name: 'commitment', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'buyName',
    inputs: [
      { name: 'label', type: 'string', internalType: 'string' },
      { name: 'secret', type: 'bytes32', internalType: 'bytes32' },
      { name: 'maxPrice', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'subnode', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'quotePrice',
    inputs: [{ name: 'label', type: 'string', internalType: 'string' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isNameAvailable',
    inputs: [{ name: 'label', type: 'string', internalType: 'string' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getLabelInfo',
    inputs: [{ name: 'label', type: 'string', internalType: 'string' }],
    outputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'purchasedAt', type: 'uint256', internalType: 'uint256' },
      { name: 'paidPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'subnode', type: 'bytes32', internalType: 'bytes32' },
      { name: 'available', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'computeCommitment',
    inputs: [
      { name: 'buyer', type: 'address', internalType: 'address' },
      { name: 'labelHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'secret', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'computeLabelHash',
    inputs: [{ name: 'label', type: 'string', internalType: 'string' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'computeSubnode',
    inputs: [{ name: 'label', type: 'string', internalType: 'string' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'i_ensRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IENS' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'i_usdc',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'i_baseNode',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'i_agentRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IAgentRegistry' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_commitMinDelay',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_commitMaxAge',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_shortPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_mediumPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_longPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_treasury',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 's_agentOnlyMode',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PurchaseCommitted',
    inputs: [
      { name: 'buyer', type: 'address', indexed: true, internalType: 'address' },
      { name: 'commitment', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'timestamp', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NamePurchased',
    inputs: [
      { name: 'buyer', type: 'address', indexed: true, internalType: 'address' },
      { name: 'label', type: 'string', indexed: false, internalType: 'string' },
      { name: 'subnode', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'paidAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PricingUpdated',
    inputs: [
      { name: 'shortPrice', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'mediumPrice', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'longPrice', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CommitWindowUpdated',
    inputs: [
      { name: 'minDelay', type: 'uint64', indexed: false, internalType: 'uint64' },
      { name: 'maxAge', type: 'uint64', indexed: false, internalType: 'uint64' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TreasuryUpdated',
    inputs: [{ name: 'treasury', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AgentOnlyModeUpdated',
    inputs: [{ name: 'enabled', type: 'bool', indexed: false, internalType: 'bool' }],
    anonymous: false,
  },
] as const;
